{
  "formatVersion": "1.1",
  "component": {
    "group": "fly",
    "module": "android.listview",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.listview-1.0.0.aar",
          "url": "android.listview-1.0.0.aar",
          "size": 62720,
          "sha512": "5e86341ea24ca0f4a29dab27a2888709aa1ed1c16f3ffb206fa087a52916d2aeb79ec0aa4b5e28cec891cd86c7412e6319578bd38d195e520add436d9c0d8e0d",
          "sha256": "75fcd4e62ecdda03fd2efb72e1a7bda0b28f02652d071a09abce0cdcecf43f61",
          "sha1": "370b6a7d063db040df628cbae8f79e61a74e5d11",
          "md5": "b5f2bbdf34a7c823c5b5d04449020216"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.listview-1.0.0.aar",
          "url": "android.listview-1.0.0.aar",
          "size": 62720,
          "sha512": "5e86341ea24ca0f4a29dab27a2888709aa1ed1c16f3ffb206fa087a52916d2aeb79ec0aa4b5e28cec891cd86c7412e6319578bd38d195e520add436d9c0d8e0d",
          "sha256": "75fcd4e62ecdda03fd2efb72e1a7bda0b28f02652d071a09abce0cdcecf43f61",
          "sha1": "370b6a7d063db040df628cbae8f79e61a74e5d11",
          "md5": "b5f2bbdf34a7c823c5b5d04449020216"
        }
      ]
    }
  ]
}
