{
  "formatVersion": "1.1",
  "component": {
    "group": "fly",
    "module": "android.listview",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.listview-1.0.1.aar",
          "url": "android.listview-1.0.1.aar",
          "size": 20091,
          "sha512": "3a069cc453113a2532d722cfd3e4d470dff2818e7538a0117ff608902d543cf65d4d483899e214dbf7bf67921fca88997579b5e7640ef15fa2a33f7d9d23c142",
          "sha256": "453870609550866a371d8dce47fb729e4d9b86ed95b3886f8c066754fd6db261",
          "sha1": "b71d30fc40213e15dacc7a568405e922599f7cc3",
          "md5": "c0bb35499d727396fd5018b2a20a82bc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.listview-1.0.1.aar",
          "url": "android.listview-1.0.1.aar",
          "size": 20091,
          "sha512": "3a069cc453113a2532d722cfd3e4d470dff2818e7538a0117ff608902d543cf65d4d483899e214dbf7bf67921fca88997579b5e7640ef15fa2a33f7d9d23c142",
          "sha256": "453870609550866a371d8dce47fb729e4d9b86ed95b3886f8c066754fd6db261",
          "sha1": "b71d30fc40213e15dacc7a568405e922599f7cc3",
          "md5": "c0bb35499d727396fd5018b2a20a82bc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android.listview-1.0.1-sources.jar",
          "url": "android.listview-1.0.1-sources.jar",
          "size": 7393,
          "sha512": "b6158ced9711b8f04ed2c0f8305b5ceb152491c68f175ab6ed37767ba1a3fe9bbca9d4978f2bb5443159bb2e7321d3890f57384f20aa917709e5eefce2f3aaac",
          "sha256": "29f8f56bc1ed03e14e689c2dd2e34f05036f160a0e471a3b0f61e4cdc7a07a0a",
          "sha1": "93018524c58a609b398eb51bef1c9d0e3dd5da65",
          "md5": "7cb63b210093e89f5e79ba1397046b3f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android.listview-1.0.1-javadoc.jar",
          "url": "android.listview-1.0.1-javadoc.jar",
          "size": 333543,
          "sha512": "c1ff193b2f9b02295db8800e4ea0eb59ff6f32bb5f58dea020458873664ee65987706512cb8a2931e503f2a049fd62739d0e9455004ea4e251bfe6aa4b3f0bc0",
          "sha256": "4c04551efd287edce653f034b987fb08f25fdc527f94d6fc784bb800d0a40e71",
          "sha1": "95bd78dd9663c61b0f5630e2904da60b696ac05b",
          "md5": "8fd75013515fae641c1c695f7d3d4010"
        }
      ]
    }
  ]
}
