{
  "formatVersion": "1.1",
  "component": {
    "group": "fly",
    "module": "android.listview",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.listview-1.0.1.aar",
          "url": "android.listview-1.0.1.aar",
          "size": 20172,
          "sha512": "9384cd657985508fc8cdc2c947aec41dbc6a4bf0e67f0146e872346d735f44c58eeddf6dbd55ac5a9d3e1b68bfc6d43992a071941efc999cac793fd9f7ed3ec6",
          "sha256": "0c65b9701f7d50bf1c35e38c8a8ba01e7f2a033d102dee3502d3dbdb82bc5199",
          "sha1": "26d37bd0e658a7b5e2d58228da6c872092fd245f",
          "md5": "9615d125b91ddad9f8d1b9dfdef933b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.listview-1.0.1.aar",
          "url": "android.listview-1.0.1.aar",
          "size": 20172,
          "sha512": "9384cd657985508fc8cdc2c947aec41dbc6a4bf0e67f0146e872346d735f44c58eeddf6dbd55ac5a9d3e1b68bfc6d43992a071941efc999cac793fd9f7ed3ec6",
          "sha256": "0c65b9701f7d50bf1c35e38c8a8ba01e7f2a033d102dee3502d3dbdb82bc5199",
          "sha1": "26d37bd0e658a7b5e2d58228da6c872092fd245f",
          "md5": "9615d125b91ddad9f8d1b9dfdef933b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android.listview-1.0.1-sources.jar",
          "url": "android.listview-1.0.1-sources.jar",
          "size": 7398,
          "sha512": "735210c07987c8cb2a73c78d659b14c3499352d3c38b5faf85792d4c2d010ef56a8f08ceb27067e3ec54c7f4bd7b29c824a1f74de84e6155880ff5957a3abb0d",
          "sha256": "780b746e7780f9b328120fcd50b39fd5bdc8f0de3d04d4c1513dc0bec50e5111",
          "sha1": "43ab99e8d177863a1e1eb8b046030dce7a1e21a2",
          "md5": "b75bb0cb6d32650d55ad538a84dffadb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android.listview-1.0.1-javadoc.jar",
          "url": "android.listview-1.0.1-javadoc.jar",
          "size": 334362,
          "sha512": "c78fa8bdd24162c1d6f6dd0a44c72358a5006ea248ffaafe926561f39b2b272d56e45b7c4992fec65dcae2a6a1d2c6e43b8234ebf9f560a4d6f89213419fda4e",
          "sha256": "a36c5b60bbf3d53612f17d2f45d19181b2f2e2c85e8407c87fd8a205f5d032ae",
          "sha1": "dc7e115eab9df43000cd0c663aea52be3c9ae651",
          "md5": "f53f8ba70a369bddb8ec8fc0448c902e"
        }
      ]
    }
  ]
}
