{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.sportservice",
    "module": "sportservice.core",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sportservice.core-1.0.5.aar",
          "url": "sportservice.core-1.0.5.aar",
          "size": 49955,
          "sha512": "59bade00f232e7b79671838d04421375f9d178375ca9b071e03b3fd20c2f5d4758ee37e3daf4ed0ca08b3b9b9bc809b13105640bdb228455d3db5d64cf2ac891",
          "sha256": "e8db20777ea17c21c5a593755583ca6068c54c24b92679980995938a309ba334",
          "sha1": "209e5e8495425e9826f7ad4681ac5eec6494c600",
          "md5": "842cfea6d49f42ef23e3c23ed698daca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sportservice.core-1.0.5.aar",
          "url": "sportservice.core-1.0.5.aar",
          "size": 49955,
          "sha512": "59bade00f232e7b79671838d04421375f9d178375ca9b071e03b3fd20c2f5d4758ee37e3daf4ed0ca08b3b9b9bc809b13105640bdb228455d3db5d64cf2ac891",
          "sha256": "e8db20777ea17c21c5a593755583ca6068c54c24b92679980995938a309ba334",
          "sha1": "209e5e8495425e9826f7ad4681ac5eec6494c600",
          "md5": "842cfea6d49f42ef23e3c23ed698daca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sportservice.core-1.0.5-sources.jar",
          "url": "sportservice.core-1.0.5-sources.jar",
          "size": 13808,
          "sha512": "2845daa5dadaf5053611fd40832a3b6aa8c1ac03199b380babf7c9c005180e256c00089ae33446436598449d4bff42061543174a8f9549d7426551d81f8a7731",
          "sha256": "ad1a2558810aed86c2260c97c16c3f2dc3369e5d0c8f0da6b13d8ddd59a9d9f5",
          "sha1": "fe0451e4475763f98dd3d4c65b5012023554259c",
          "md5": "f9b70fd8f7aca7fba76c0c71a3ddeea2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sportservice.core-1.0.5-javadoc.jar",
          "url": "sportservice.core-1.0.5-javadoc.jar",
          "size": 398105,
          "sha512": "34ca845acd4a47ff27ca5a173dbb5e5a01d24944efeb639440bf1551b0aa7a2ed8068c941f92b3f8ed32a7ac64769d3a3e3a051f6d25a4b9e6425847d7007685",
          "sha256": "a5b4ae3fc620067bf7706ea1913d76436a87ac9b2164c11b5800f7b59a953955",
          "sha1": "bbf58d24fc0021157c3c41a63dbfed31b79b5f9d",
          "md5": "2d69625ea9d1af58bc449ee0396a292d"
        }
      ]
    }
  ]
}
