{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun",
    "module": "general",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "general-1.1.2.aar",
          "url": "general-1.1.2.aar",
          "size": 201811,
          "sha512": "dc91dd73d5d65918aa172b32d567e00bb3718180f7f8f2bafd5299aca85c869175a34c944b403c96d576aa182080267027b948742864a8a5eafe019c7044bd94",
          "sha256": "9330bb7d03336b56032cff60e34d237f5df50e9e9a824b6d457e9b3e5e53446f",
          "sha1": "bf4560f479671e8ac03db8e010a10b0dadcff437",
          "md5": "b87926cc9d659255359cd4d88f1c683f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "me.jahnen.libaums",
          "module": "core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "general-1.1.2.aar",
          "url": "general-1.1.2.aar",
          "size": 201811,
          "sha512": "dc91dd73d5d65918aa172b32d567e00bb3718180f7f8f2bafd5299aca85c869175a34c944b403c96d576aa182080267027b948742864a8a5eafe019c7044bd94",
          "sha256": "9330bb7d03336b56032cff60e34d237f5df50e9e9a824b6d457e9b3e5e53446f",
          "sha1": "bf4560f479671e8ac03db8e010a10b0dadcff437",
          "md5": "b87926cc9d659255359cd4d88f1c683f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "general-1.1.2-sources.jar",
          "url": "general-1.1.2-sources.jar",
          "size": 78669,
          "sha512": "b8de006f9ac732fbf0df9214550f4ec58d5ca06e75cc7a46c712c612eb44e0fc2680de9011bedca8e0816e62afe5707f3b787c166c720ec2e8e3e932d3627d40",
          "sha256": "31927997468b2cfc31a023ff7d976a1559891a01bcf1e1f420fd113685688f28",
          "sha1": "d36c2355880dfdc020568c0cafcb954a7104cbc2",
          "md5": "144463b0f6326db225e22daca8b79dde"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "general-1.1.2-javadoc.jar",
          "url": "general-1.1.2-javadoc.jar",
          "size": 671922,
          "sha512": "3478b7fd88e2b94bf48edd27327b713136c787633da42667dea54b85e8281061b5f0dd57558d19b6951886b5904bf92bcf605d2560269fecff0b36534b9c11ed",
          "sha256": "ec45f2280a447be93ee7ff496c6dfac39185da2f96b683438c630d915132f46c",
          "sha1": "aed9ffe171de7a61901110dd1daa04da048d2ce9",
          "md5": "afc1243ef529980a43dc0454aeee1b01"
        }
      ]
    }
  ]
}
