{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.frameworks",
    "module": "core-aidl",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "core-aidl-1.0.3.aar",
          "url": "core-aidl-1.0.3.aar",
          "size": 51068,
          "sha512": "b794916e70fce4938f07f5ebb8200381d8170ef0cb0290f029bbf5fa2089544488861306891083db11c8114df7279b44ef6a79551a6fca1477d4fc5350c800a9",
          "sha256": "b832c8bf270aba30d24c726cfad3d9e506433ef7a282f700fd56b3972bf3548b",
          "sha1": "1e0eafdeb2112cf17970cacdfcba26a2fe9442e1",
          "md5": "e71cb183f8eb7a7b509e9855e83f392b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20-RC"
          }
        }
      ],
      "files": [
        {
          "name": "core-aidl-1.0.3.aar",
          "url": "core-aidl-1.0.3.aar",
          "size": 51068,
          "sha512": "b794916e70fce4938f07f5ebb8200381d8170ef0cb0290f029bbf5fa2089544488861306891083db11c8114df7279b44ef6a79551a6fca1477d4fc5350c800a9",
          "sha256": "b832c8bf270aba30d24c726cfad3d9e506433ef7a282f700fd56b3972bf3548b",
          "sha1": "1e0eafdeb2112cf17970cacdfcba26a2fe9442e1",
          "md5": "e71cb183f8eb7a7b509e9855e83f392b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-aidl-1.0.3-sources.jar",
          "url": "core-aidl-1.0.3-sources.jar",
          "size": 13345,
          "sha512": "5a5e5af29b9665685f34e75c55f934cffae585dcc99eb0d2e8f7674d89804ec5802fbb8b0625707f7eccb059d5274bf33e4092c71e0d20b1dcbf7828c90b470b",
          "sha256": "8124e1bdb65c91d6a381563054a8f686fb2d33728d3a0a2b61ad1addeeae4218",
          "sha1": "069dbe946e842d00dd3605fe0b4e663d692855e0",
          "md5": "6b9b76cd0c3e4a50a849fb2945ff4322"
        }
      ]
    }
  ]
}
