{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.iconsole",
    "module": "iconsole.login",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "iconsole.login-1.0.2.aar",
          "url": "iconsole.login-1.0.2.aar",
          "size": 94553,
          "sha512": "ed94e1fd8e718cae21bb0df865b36618ed632b6169c31011d13fb99d144094da808718affb35bb90b570278119bc4358780ef1f4dc1af5df6a240783d6c4a5d2",
          "sha256": "c87dc336908728ec86340c1750b375bb09084cabaa9b0582cd826454233e49ab",
          "sha1": "7d218c6576b9969da3405e9195309e5c8ce5e3cc",
          "md5": "3fdf7c6a162a829150dbf5f1eba51a6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "iconsole.login-1.0.2.aar",
          "url": "iconsole.login-1.0.2.aar",
          "size": 94553,
          "sha512": "ed94e1fd8e718cae21bb0df865b36618ed632b6169c31011d13fb99d144094da808718affb35bb90b570278119bc4358780ef1f4dc1af5df6a240783d6c4a5d2",
          "sha256": "c87dc336908728ec86340c1750b375bb09084cabaa9b0582cd826454233e49ab",
          "sha1": "7d218c6576b9969da3405e9195309e5c8ce5e3cc",
          "md5": "3fdf7c6a162a829150dbf5f1eba51a6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "iconsole.login-1.0.2-sources.jar",
          "url": "iconsole.login-1.0.2-sources.jar",
          "size": 17426,
          "sha512": "abc2c3eb7e5228774f7506a7fc5bfd8f1866a4f47ea1ee4e3f06181d0b263a5eac68fb514294efcada297a8e112cbf7352f30e29fe4b27bf18797445d8e89201",
          "sha256": "a9f44047b53b8464d1996e45ee4f551cca34fa1b7befca9ddfa163e652845877",
          "sha1": "3d1fb5b35b987ca52926e16ebe47cd21022dbc8c",
          "md5": "56326c46413cea88aa8d0be1ca08ca2f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "iconsole.login-1.0.2-javadoc.jar",
          "url": "iconsole.login-1.0.2-javadoc.jar",
          "size": 437553,
          "sha512": "1b2e305c4492d51f3584958f39c336baeb3d493910a451dc377db0bb21e23d8be34e369e028c4c59285af4ae0cb2accc7a50260b6741913af6e74a75d7b070e6",
          "sha256": "9ff757e2a7e35b0934225a0a99264f10da00ea8a7df7f10deab81676ddc079de",
          "sha1": "3680ac43b5f0a88951e69d7f316c9397a17b6689",
          "md5": "0c89c6c3de7fa1e953f1734f507f2172"
        }
      ]
    }
  ]
}
