{
  "formatVersion": "1.1",
  "component": {
    "group": "fly",
    "module": "android.service",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.service-1.0.0.aar",
          "url": "android.service-1.0.0.aar",
          "size": 13865,
          "sha512": "aca9d71948d7f1317a89d4732dc21d26b752448feabe7a16f2f7fdb7e0e8ed169468dfb1d27d52c781764ef62b47400f94edb7c93eacf8b35261fc7c13e87c58",
          "sha256": "646e12d7ec4f1c980e6c8f14a9a473757e185961388020ecaaa57ed929329928",
          "sha1": "5313c6ea63467b8f52f12cadc6b3820908b06cf6",
          "md5": "f868a23e46a3fc80aad7123a5793786c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.service-1.0.0.aar",
          "url": "android.service-1.0.0.aar",
          "size": 13865,
          "sha512": "aca9d71948d7f1317a89d4732dc21d26b752448feabe7a16f2f7fdb7e0e8ed169468dfb1d27d52c781764ef62b47400f94edb7c93eacf8b35261fc7c13e87c58",
          "sha256": "646e12d7ec4f1c980e6c8f14a9a473757e185961388020ecaaa57ed929329928",
          "sha1": "5313c6ea63467b8f52f12cadc6b3820908b06cf6",
          "md5": "f868a23e46a3fc80aad7123a5793786c"
        }
      ]
    }
  ]
}
