{
  "formatVersion": "1.1",
  "component": {
    "group": "jerome.com.usbcamera",
    "module": "usbcamera",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "usbcamera-1.0.1.aar",
          "url": "usbcamera-1.0.1.aar",
          "size": 108122,
          "sha512": "0f4f7a6f2e755258743e1d76f80c51ba6367e0058ecb39c6d2ca5bd788667bda8b28771b3be015efcbf6a51a21eff2948245e3a37a50826ff993cf7fe7814a65",
          "sha256": "1a3bc9ce9d88d166510758156e458bdeaaacdbbf7e028e12ca149b614ec528c1",
          "sha1": "b5f9148538b352ed6e90ec82eca3ab7edcdb8e1b",
          "md5": "7c2e7629e82d6575bba8370fc23bee7c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "usbcamera-1.0.1.aar",
          "url": "usbcamera-1.0.1.aar",
          "size": 108122,
          "sha512": "0f4f7a6f2e755258743e1d76f80c51ba6367e0058ecb39c6d2ca5bd788667bda8b28771b3be015efcbf6a51a21eff2948245e3a37a50826ff993cf7fe7814a65",
          "sha256": "1a3bc9ce9d88d166510758156e458bdeaaacdbbf7e028e12ca149b614ec528c1",
          "sha1": "b5f9148538b352ed6e90ec82eca3ab7edcdb8e1b",
          "md5": "7c2e7629e82d6575bba8370fc23bee7c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "usbcamera-1.0.1-sources.jar",
          "url": "usbcamera-1.0.1-sources.jar",
          "size": 39657,
          "sha512": "323a54a2a1a2673bbb0dd96d4645e3b942a7e58edbb201809e41bfb2709b524e77353f0f20f3b0b0245fb5fb8ee031caa49d817962be779d0c1e89527f0ce847",
          "sha256": "676c5661c2d4647f02fcbe646457797fce69a719e821a5c3aea33f48f5028d64",
          "sha1": "e55c8f7d1aecf132f5ea3f9b71d21648fcccb6c1",
          "md5": "cd3cb634b5b0a85c2268ada359f07e3f"
        }
      ]
    }
  ]
}
