{
  "formatVersion": "1.1",
  "component": {
    "group": "fly",
    "module": "android.logcat",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.logcat-1.0.0.aar",
          "url": "android.logcat-1.0.0.aar",
          "size": 25076,
          "sha512": "9fb1ff13c4537ed31f7b5e83d7dfa4a8915de03f190c979cd70a8071f3419d519c863b3600b26719723bd02535331d5aa2ae0743a00b88d8512993e20730c290",
          "sha256": "d154feb8af5fd3357e9dfc002e332efe05045d653840c933b407e5df8c980629",
          "sha1": "d4cd0f2dfda700ff8bb5c6551c5f1638ac3043b4",
          "md5": "ae96009317657ee3ee37c92cce8fe6a1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.logcat-1.0.0.aar",
          "url": "android.logcat-1.0.0.aar",
          "size": 25076,
          "sha512": "9fb1ff13c4537ed31f7b5e83d7dfa4a8915de03f190c979cd70a8071f3419d519c863b3600b26719723bd02535331d5aa2ae0743a00b88d8512993e20730c290",
          "sha256": "d154feb8af5fd3357e9dfc002e332efe05045d653840c933b407e5df8c980629",
          "sha1": "d4cd0f2dfda700ff8bb5c6551c5f1638ac3043b4",
          "md5": "ae96009317657ee3ee37c92cce8fe6a1"
        }
      ]
    }
  ]
}
