{
  "formatVersion": "1.1",
  "component": {
    "group": "fly",
    "module": "android.logcat",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.logcat-1.0.0.aar",
          "url": "android.logcat-1.0.0.aar",
          "size": 22796,
          "sha512": "a7b130a77f87e774b13af790a58d64f428f355d5e6e4fcb711b3c63b76bd34ca9c741b02beffe04afe4b792636104c10fa3ffb5c377aa0c1114fad60a5269bf0",
          "sha256": "8f1843a12f5f58397d25cbafb0b819decbdae25cacad059ec564b5a289b4370f",
          "sha1": "85771d9eaf6c5cd5e4695131d833f8335e6fb97c",
          "md5": "68838a9794c0bac627514eae6036dd9b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.logcat-1.0.0.aar",
          "url": "android.logcat-1.0.0.aar",
          "size": 22796,
          "sha512": "a7b130a77f87e774b13af790a58d64f428f355d5e6e4fcb711b3c63b76bd34ca9c741b02beffe04afe4b792636104c10fa3ffb5c377aa0c1114fad60a5269bf0",
          "sha256": "8f1843a12f5f58397d25cbafb0b819decbdae25cacad059ec564b5a289b4370f",
          "sha1": "85771d9eaf6c5cd5e4695131d833f8335e6fb97c",
          "md5": "68838a9794c0bac627514eae6036dd9b"
        }
      ]
    }
  ]
}
