{
  "formatVersion": "1.1",
  "component": {
    "group": "fly",
    "module": "android.permission",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.permission-1.0.4.aar",
          "url": "android.permission-1.0.4.aar",
          "size": 22298,
          "sha512": "454c09ac7baf231513a85791966ac38e1791fe99ba6aca6d2b5fe9e051925843b1394c0d3e6bf0052153636714375733b61517efaed9637a82e7f1e129015bb3",
          "sha256": "f4a8272725c2d51b80ef386437ca4c5f16c3d52620bb8e1dc5c1bd8e314e72e0",
          "sha1": "32c87f9f70662bfdcd3aa368aca30bf34152fab7",
          "md5": "a65f138c52f57f1e15d066dda18d6ee9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.permission-1.0.4.aar",
          "url": "android.permission-1.0.4.aar",
          "size": 22298,
          "sha512": "454c09ac7baf231513a85791966ac38e1791fe99ba6aca6d2b5fe9e051925843b1394c0d3e6bf0052153636714375733b61517efaed9637a82e7f1e129015bb3",
          "sha256": "f4a8272725c2d51b80ef386437ca4c5f16c3d52620bb8e1dc5c1bd8e314e72e0",
          "sha1": "32c87f9f70662bfdcd3aa368aca30bf34152fab7",
          "md5": "a65f138c52f57f1e15d066dda18d6ee9"
        }
      ]
    }
  ]
}
