{
  "formatVersion": "1.1",
  "component": {
    "group": "fly",
    "module": "android.permission",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.permission-1.0.3.aar",
          "url": "android.permission-1.0.3.aar",
          "size": 22294,
          "sha512": "ba7b1a1ef365fb0c721234aa152b0629d19ae77127561e89e3d6554f11fda8658790ee29ed446c32dde5b255deb2924d4788968f79a1f62d66349757c0036e96",
          "sha256": "50c1117d9b4500a4552141b0026be7d2e41a710385c1e3d8bdc5f2e6f903f3a5",
          "sha1": "7b1044b2d5d60af7f6399386d2ebbb696cc12980",
          "md5": "aa6497ee33dd18e53cf954c2f139e436"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android.permission-1.0.3.aar",
          "url": "android.permission-1.0.3.aar",
          "size": 22294,
          "sha512": "ba7b1a1ef365fb0c721234aa152b0629d19ae77127561e89e3d6554f11fda8658790ee29ed446c32dde5b255deb2924d4788968f79a1f62d66349757c0036e96",
          "sha256": "50c1117d9b4500a4552141b0026be7d2e41a710385c1e3d8bdc5f2e6f903f3a5",
          "sha1": "7b1044b2d5d60af7f6399386d2ebbb696cc12980",
          "md5": "aa6497ee33dd18e53cf954c2f139e436"
        }
      ]
    }
  ]
}
