{
  "formatVersion": "1.1",
  "component": {
    "group": "com.boqun.sportservice",
    "module": "sportservice.core",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sportservice.core-1.0.3.aar",
          "url": "sportservice.core-1.0.3.aar",
          "size": 47149,
          "sha512": "ec61b55ad589012fefdf975ab0bf25c1364adbc597cd9c21ee933cb27daa538e368470dfc32070f6fc4bbebbf79c03f7b809ee63043704db6bacaa240eade137",
          "sha256": "63db59c5180e913ec810d6337c55c36d136c7eb7c05921e54efe85ca6b2832cf",
          "sha1": "fab1445cc88604c721fb6db74fb063239fd625de",
          "md5": "565759456387f90c542bb280d0cfdebd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sportservice.core-1.0.3.aar",
          "url": "sportservice.core-1.0.3.aar",
          "size": 47149,
          "sha512": "ec61b55ad589012fefdf975ab0bf25c1364adbc597cd9c21ee933cb27daa538e368470dfc32070f6fc4bbebbf79c03f7b809ee63043704db6bacaa240eade137",
          "sha256": "63db59c5180e913ec810d6337c55c36d136c7eb7c05921e54efe85ca6b2832cf",
          "sha1": "fab1445cc88604c721fb6db74fb063239fd625de",
          "md5": "565759456387f90c542bb280d0cfdebd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sportservice.core-1.0.3-sources.jar",
          "url": "sportservice.core-1.0.3-sources.jar",
          "size": 13192,
          "sha512": "3abae03d70a9ed60afef6c73ed19fc9347f76c50a19c50036ed55b50afe70f2934dde5bae70b8d867441bd3c3cf54d12c870c9ddb5fb75b88b48d85d45738d27",
          "sha256": "96d6102f74e6c0c3527dd3e19f8621c61268c7d1bb038f5f81545bc8c8760b35",
          "sha1": "658ba35d0b4bba38faf4e88c2847ead37da792e4",
          "md5": "a02d5bddc43581666f5b32635050898d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sportservice.core-1.0.3-javadoc.jar",
          "url": "sportservice.core-1.0.3-javadoc.jar",
          "size": 391880,
          "sha512": "fed3980c960167898887976d53eb519dd67c9bf8b5938d7e5a5425aa170d61b29df1d41fed448470a2e9c522f940ad9a135b876f0d5c6f6499ce071f05ec26d4",
          "sha256": "b37f9eae48c029284797b5cf741557a6e4d65cf92423a3a9933a43f10402365a",
          "sha1": "1e6a12359e9b437338c5e95d3f6b45d8e70fe307",
          "md5": "23983cd4dfb7fc777159e9cb39210111"
        }
      ]
    }
  ]
}
